name: coverage

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "4.14"
          opam-local-packages: $${ matrix.opam-local-packages }}

      - name: Install Opam dependencies
        run: |
          opam install . --deps-only --with-test
          opam install bisect_ppx

      - name: Run tests with coverage instrumentation
        run: opam exec -- dune runtest --instrument-with bisect_ppx

      - name: Send coverage report to Codecov
        if: github.repository_owner == 'mirage'
        run: opam exec -- bisect-ppx-report send-to Codecov
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
